>P1;E2_target
sequence:E2_target:384:A:752:A:E2 protein:HCV: 0.00: 0.00
ETHVTGGNAGRTTAGLVGLLTPGAKQNIQLINTNGSWHINSTALNCNES
LNTGWLAGLFY
QHKFNSSGCPERLTSCRRLTDFAQGWGPISYANGSGLDERPYCWHYPPR
PCGIVPAKSVC
GPVYCFTPSPVVVGTTDRSGAPTYSWGANDTDVFVLNNTRPPLGNWFGC
TWMNSTGFTKV
CGAPPCVIGGVGNNTLLCPTDCFRKHPEATYSRCGSGPWITPRCMVDYP
YRLWHYPCTIN
YTIFKVRMYVGGVEHRLEAACNWTRGERCDLEDRDRSELSPLLLSTTQW
QVLPCSFTTLP
ALSTGLIHLHQNIVDVQYLYGVGSSIASWAIKWEYVVLLFLLLADARVC
SCLWMMLLISQ
AEA*

>P1;8RJJ_B_CLEAN
structureX:8RJJ_B_CLEAN:384:B:752:B:E2 protein:HCV: 2.00: 0.19
ETYVTGGSVAHSARGLTSLFSMGAKQKLQLVNTNGSWHINSTALNC-NE
SINTGFIAGLFY
YHKFNSTGCPQRLSSCKPIISFRQGWGPLTDANITGPSDDRPYCWHYAP
RPCSVVPASSV
CGPVYCFTPSPVVVGTTDIKGKPTYNWGENETDVFLLESLRPPSGR-WF
GCAWMNSTGFLK
TCGAPPCNIYGG-----NETDLFCPTDCFRKHPEATYSRCGAGPWLTPR
CMVDYPYRLWH
YPCTVNFTLFKVRMFVGGFEHRFTAACNWTRGERCNIEDRDRSEQHPLL
HSTTELAILPC
SFTPMPALSTLGIHLHQNIVDVQYLYG--------ALKWEYVVLLFLLL
ADARVCSCLWM
MLLISQAEA*

>P1;8RK0_B_CLEAN
structureX:8RK0_B_CLEAN:384:B:710:B:E2 protein:HCV: 2.00: 0.21
ETYVTGGSVAHSARGLTSLFSMGAKQKLQLVNTNGSWHINSTALNC-NE
SINTGFIAGLFY
YHKFNSTGCPQRLSSCKPIISFRQGWGPLTDANITGPSDDRPYCWHYAP
RPCSVVPASSV
CGPVYCFTPSPVVVGTTDIKGKPTYNWGENETDVFLLESLRPPSGR-WF
GCAWMNSTGFLK
TCGAPPCNIYGG-----NETDLFCPTDCFRKHPEATYSRCGAGPWLTPR
CMVDYPYRLWH
YPCTVNFTLFKVRMFVGGFEHRFTAACNWTRGERCNIEDRDRSEQHPLL
HSTTELAILPC
SFTPMPALSTLGIHLHQNIVDVQYLYG----------------------
------------
---------*